# Generated by Django 5.2.14 on 2026-06-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20, unique=True)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('consumer', 'Consumer'), ('elder', 'Elder User')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('password', models.CharField(max_length=255)),
                ('trusted_contact_name', models.CharField(blank=True, max_length=100)),
                ('trusted_contact_phone', models.CharField(blank=True, max_length=15)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
