# Generated by Django 5.2.15 on 2026-06-28 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employment_type', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=30)),
                ('dependents', models.PositiveIntegerField(default=0)),
                ('financial_goal', models.CharField(max_length=100)),
                ('risk_appetite', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
            ],
        ),
    ]
