# Generated by Django 5.2.15 on 2026-07-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_financialprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialprofile',
            name='financial_goal',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='risk_appetite',
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='credit_card_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='education_loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='existing_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='financial_goals',
            field=models.TextField(blank=True, help_text='Comma separated goals'),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='home_loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='monthly_savings_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='other_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='other_financial_goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='other_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='personal_loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='preferred_monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='preferred_savings_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='receive_ai_recommendations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='spending_alert_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='employment_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Salaried', 'Salaried'), ('Self-Employed', 'Self-Employed'), ('Business Owner', 'Business Owner'), ('Freelancer', 'Freelancer'), ('Other', 'Other')], default='Salaried', max_length=50),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=30),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
