# Generated by Django 5.2.15 on 2026-08-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_financialprofile_financial_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='aadhaar_analysis_status',
            field=models.CharField(default='Not Analyzed', max_length=50),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='aadhaar_image',
            field=models.ImageField(blank=True, null=True, upload_to='identity_documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='aadhaar_last4',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pan_analysis_status',
            field=models.CharField(default='Not Analyzed', max_length=50),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='identity_documents/pan/'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pan_number_masked',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
