# Generated by Django 5.2.15 on 2026-08-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_aadhaar_analysis_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='aadhaar_image',
            new_name='aadhaar_document',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='pan_image',
            new_name='pan_document',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='aadhaar_analysis_status',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='aadhaar_last4',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='pan_analysis_status',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='pan_number_masked',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='aadhaar_last_four',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='aadhaar_ocr_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pan_ocr_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pan_verified',
            field=models.BooleanField(default=False),
        ),
    ]
