# Generated by Django 5.2.14 on 2026-06-12 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('banking', '0003_fixeddeposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenure_months', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maturity_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maturity_date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
            ],
        ),
    ]
