# Generated by Django 5.2.14 on 2026-06-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_recurringdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringdeposit',
            name='installments_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringdeposit',
            name='total_installments',
            field=models.IntegerField(default=0),
        ),
    ]
