# Generated by Django 5.2.14 on 2026-06-17 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_recurringdeposit_installments_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringdeposit',
            name='next_due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
