# Generated by Django 5.2.14 on 2026-06-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_passionfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='channel',
            field=models.CharField(default='Web', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Completed', max_length=20),
        ),
    ]
