# Generated by Django 5.2.15 on 2026-06-28 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_financialprofile'),
        ('banking', '0008_transaction_category_transaction_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('scheduled_datetime', models.DateTimeField()),
                ('purpose', models.CharField(choices=[('Personal', 'Personal'), ('Bill Payment', 'Bill Payment'), ('Investment', 'Investment'), ('Salary', 'Salary'), ('Other', 'Other')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
            ],
        ),
    ]
