# Generated by Django 5.2.15 on 2026-08-21 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_financialprofile_financial_goal_and_more'),
        ('banking', '0009_scheduledwithdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='accounts.useraccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'account_number')},
            },
        ),
    ]
