# Generated by Django 5.2.15 on 2026-08-21 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_financialprofile_financial_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('cleaned_text', models.TextField(blank=True)),
                ('processed_text', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, max_length=100)),
                ('banking_intent', models.CharField(blank=True, max_length=150)),
                ('ethical_classification', models.CharField(blank=True, max_length=150)),
                ('ml_risk_prediction', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.CharField(max_length=50)),
                ('risk_score', models.FloatField(default=0)),
                ('manipulation_score', models.FloatField(default=0)),
                ('transparency_score', models.FloatField(default=0)),
                ('offer_category', models.CharField(blank=True, max_length=100)),
                ('detected_patterns', models.JSONField(blank=True, default=list)),
                ('pattern_analysis', models.JSONField(blank=True, default=list)),
                ('recommendation', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.useraccount')),
            ],
            options={
                'verbose_name': 'Offer Scan History',
                'verbose_name_plural': 'Offer Scan Histories',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
